spring.application.name=device-support

spring.datasource.url=jdbc:postgresql://dpg-daq4cd6gekts73bhit5g-a.oregon-postgres.render.com:5432/db2026g2
spring.datasource.username=db2026g2_user
spring.datasource.password=s7XBmE63hAQZk8QcW8MoqTzNK3ekFpm6

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect